import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Google Developer Student Clubs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-signin-client_id"
          content="1010379975924-uu04sdp61suebvkkvshj7vgbcu4aami2.apps.googleusercontent.com"
        ></meta>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
